"""Add reminders_sent field to Todo model

Revision ID: 536a15a51913
Revises: 887bbfa3acac
Create Date: 2025-11-16 22:47:58.413152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536a15a51913'
down_revision = '887bbfa3acac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminders_sent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('reminders_sent')

    # ### end Alembic commands ###
