"""Add completed_at field to Todo model

Revision ID: 887bbfa3acac
Revises: 
Create Date: 2025-11-16 17:56:52.781366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887bbfa3acac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
